name: "Formatting check (ormolu)"
on:
  pull_request:
  push:
jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrkkrp/ormolu-action@v6
  build:
    runs-on: ubuntu-latest
    needs: ormolu
